### ISSUE TITLE
当我尝试在Flux放大中接入Controlnet Upscaler报错：KSampler start (6) + length (1) exceeds dimension size (6).

### ISSUE THREAD

**Issue by LiJT** [TTPlanetPig/Comfyui_TTP_Toolset#10]
汤团猪大佬您好
我根据您这个 https://github.com/TTPlanetPig/Comfyui_TTP_Toolset/blob/main/examples/Hunyuan_8Mega_Pixel_image_upscale_process_with_tile_cn.png 这张图片里的工作流，把模型替换成了Flux, 然后重新排了一下版，发现在flux中无法使用和您相同的放大逻辑进行放大。会直接报错 

> KSampler start (6) + length (1) exceeds dimension size (6).

我的工作流您能否帮忙看看
[TTPlanet Github Issue.json](https://github.com/user-attachments/files/17226620/TTPlanet.Github.Issue.json)

请问这是哪里出了问题？Hunyuan和Flux不都是属于DiT模型么？为什么hunyuan可以实现但flux不可以？这个问题是出在了哪里？谢谢您！

Prompt executed in 0.18 seconds
got prompt
Requested to load AutoencodingEngine
Loading 1 new model
loaded completely 0.0 159.87335777282715 True
Processing interrupted
Prompt executed in 9.55 seconds
got prompt
!!! Exception during processing !!! start (6) + length (1) exceeds dimension size (6).
Traceback (most recent call last):
  File "E:\ComfyUI-aki-v1.3\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\ComfyUI-aki-v1.3\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\ComfyUI-aki-v1.3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\ComfyUI-aki-v1.3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\ComfyUI-aki-v1.3\nodes.py", line 1434, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "E:\ComfyUI-aki-v1.3\nodes.py", line 1401, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 22, in informative_sample
    raise e
  File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)  # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
  File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 420, in motion_sample
    return orig_comfy_sample(model, noise, *args, **kwargs)
  File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\sampling.py", line 116, in acn_sample
    return orig_comfy_sample(model, *args, **kwargs)
  File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 117, in uncond_multiplier_check_cn_sample
    return orig_comfy_sample(model, *args, **kwargs)
  File "E:\ComfyUI-aki-v1.3\comfy\sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-TiledDiffusion\utils.py", line 51, in KSampler_sample
    return orig_fn(*args, **kwargs)
  File "E:\ComfyUI-aki-v1.3\comfy\samplers.py", line 829, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "E:\ComfyUI-aki-v1.3\comfy\samplers.py", line 729, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "E:\ComfyUI-aki-v1.3\comfy\samplers.py", line 716, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "E:\ComfyUI-aki-v1.3\comfy\samplers.py", line 695, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-TiledDiffusion\utils.py", line 34, in KSAMPLER_sample
    return orig_fn(*args, **kwargs)
  File "E:\ComfyUI-aki-v1.3\comfy\samplers.py", line 600, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "E:\ComfyUI-aki-v1.3\python\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "E:\ComfyUI-aki-v1.3\comfy\k_diffusion\sampling.py", line 202, in sample_heun
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "E:\ComfyUI-aki-v1.3\comfy\samplers.py", line 299, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "E:\ComfyUI-aki-v1.3\comfy\samplers.py", line 682, in __call__
    return self.predict_noise(*args, **kwargs)
  File "E:\ComfyUI-aki-v1.3\comfy\samplers.py", line 685, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "E:\ComfyUI-aki-v1.3\comfy\samplers.py", line 279, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "E:\ComfyUI-aki-v1.3\comfy\samplers.py", line 153, in calc_cond_batch
    p = get_area_and_mult(x, x_in, timestep)
  File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-TiledDiffusion\utils.py", line 66, in get_area_and_mult
    return store.get_area_and_mult(*args, **kwargs)
  File "E:\ComfyUI-aki-v1.3\comfy\samplers.py", line 61, in get_area_and_mult
    m = mult.narrow(i + 2, t, 1)
RuntimeError: start (6) + length (1) exceeds dimension size (6).

Prompt executed in 0.13 seconds

**Comment by TTPlanetPig** [comment]
非常不建议使用controlnet upscaler 模型，因为其实不需要，它的存在会裂化画质。
如果你一定要用，参考我混元的工作流逻辑，替换相关节点即可工作。最近繁忙，我之后会看看你工作流的逻辑，但是请严格参考我混元的逻辑，来完成流程搭建。
