### ISSUE TITLE
error with TTP_image_assy node: index 2 out of bounds?

### ISSUE THREAD

**Issue by EricRollei** [TTPlanetPig/Comfyui_TTP_Toolset#11]
Hi,
Since updating my comfy, I'm experiencing the following error when previously in the last days it was working fine.  I am guessing something in one of the other node sets or comfy has changed and caused the problem, but I'm reporting here since I don't know what it is. 

!!! Exception during processing !!! index 2 is out of bounds for dimension 0 with size 2
Traceback (most recent call last):
  File "A:\Comfy_Dec\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Dec\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Dec\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "A:\Comfy_Dec\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Dec\ComfyUI\custom_nodes\Comfyui_TTP_Toolset\TTP_toolsets.py", line 216, in assemble_image
    row_image = tensor2pil(tiles[row * num_cols].unsqueeze(0))
                           ~~~~~^^^^^^^^^^^^^^^^
IndexError: index 2 is out of bounds for dimension 0 with size 2

![image](https://github.com/user-attachments/assets/627edd92-8ba6-4d6d-a71b-dc77666841da)

**Comment by YiK1991** [comment]
Same

**Comment by TTPlanetPig** [comment]
please check if you recently updated the florence-2 node. the new update looks damage the logic for batch image. For quick solution, please change another Florence node or other vision model node for now. I will adjust the workflow soon. My custom node only need opencv, so should be no issue to continue work on this logic.

**Comment by TTPlanetPig** [comment]
checked 9/10 florence works fine. defualt comfyui works fine

**Comment by jasoncow007** [comment]
> checked 9/10 florence works fine. defualt comfyui works fine
u mean loop back to Sep.10th version?

**Comment by TTPlanetPig** [comment]
> > checked 9/10 florence works fine. defualt comfyui works fine
> > u mean loop back to Sep.10th version?

only for florence！ my node only require opencv

**Comment by hanyouming** [comment]
同样的问题，请问具体怎么操作啊

**Comment by hanyouming** [comment]
期待老师，早日解决问题。

**Comment by TTPlanetPig** [comment]
同志们，这个真的不是我的节点问题，是前置节点或者别的节点破坏了依赖，现在察下来是florence的节点，你们看看换一个？我的最新的jc2节点就没有问题

**Comment by TTPlanetPig** [comment]
try my jc2 node to replace the florence-2
https://github.com/TTPlanetPig/Comfyui_JC2/pull/2

**Comment by yamanacn** [comment]
更新easyuse插件到最新可以解决这个问题
Updating the easyuse plugin to the latest version can solve this problem.
