### ISSUE TITLE
NameError: name 'apply_gaussian_blur' is not defined

### ISSUE THREAD

**Issue by EasyComfyui** [TTPlanetPig/Comfyui_TTP_Toolset#15]
# ComfyUI Error Report
## Error Details
- **Node ID:** 189
- **Node Type:** TTPlanet_Tile_Preprocessor_Simple
- **Exception Type:** NameError
- **Exception Message:** name 'apply_gaussian_blur' is not defined
## Stack Trace
```
  File "F:\demo\backup\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\demo\backup\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\demo\backup\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "F:\demo\backup\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\demo\backup\ComfyUI\custom_nodes\Comfyui_TTP_Toolset\TTP_toolsets.py", line 52, in process_image
    img_np = apply_gaussian_blur(resized_img, ksize=int(blur_strength), sigmaX=blur_strength / 2)
             ^^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.3.0-3-g41444b5
- **Arguments:** ComfyUI\main.py --windows-standalone-build --front-end-version Comfy-Org/ComfyUI_frontend@latest
- **OS:** nt
- **Python Version:** 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.4.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 25769279488
  - **VRAM Free:** 24438112256
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs
```
2024-11-21T21:21:45.257829 - [Crystools [0;32mINFO[0m] GPU/s:
2024-11-21T21:21:45.274415 - [Crystools [0;32mINFO[0m] 0) NVIDIA GeForce RTX 3090
2024-11-21T21:21:45.274415 - [Crystools [0;32mINFO[0m] NVIDIA Driver: 566.03
2024-11-21T21:21:47.513791 - [ComfyUI-Easy-Use] server: 2024-11-21T21:21:47.513791 - v1.2.5 2024-11-21T21:21:47.513791 - Loaded2024-11-21T21:21:47.513791 - 
2024-11-21T21:21:47.513791 - [ComfyUI-Easy-Use] web root: 2024-11-21T21:21:47.514790 - F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-Easy-Use\web_version/v2 2024-11-21T21:21:47.514790 - Loaded2024-11-21T21:21:47.514790 - 
2024-11-21T21:21:47.718435 - Total VRAM 24576 MB, total RAM 49088 MB
2024-11-21T21:21:47.718435 - pytorch version: 2.4.1+cu124
2024-11-21T21:21:47.718435 - xformers version: 0.0.28.post1
2024-11-21T21:21:47.718435 - Set vram state to: NORMAL_VRAM
2024-11-21T21:21:47.719354 - Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
2024-11-21T21:21:47.739413 - ### Loading: ComfyUI-Impact-Pack (V7.11.4)2024-11-21T21:21:47.740415 - 
2024-11-21T21:21:47.742414 - [Impact Pack] Wildcards loading done.2024-11-21T21:21:47.742414 - 
2024-11-21T21:21:47.762979 - ### Loading: ComfyUI-Inspire-Pack (V1.6.1)2024-11-21T21:21:47.763979 - 
2024-11-21T21:21:49.178057 - ### Loading: ComfyUI-Manager (V2.51.9)2024-11-21T21:21:49.178310 - 
2024-11-21T21:21:49.302614 - ### ComfyUI Revision: 2845 [41444b52] | Released on '2024-11-21'2024-11-21T21:21:49.302614 - 
2024-11-21T21:21:49.714842 - [SD Prompt Reader] 2024-11-21T21:21:49.714842 - Node version: 1.3.42024-11-21T21:21:49.714842 - 
2024-11-21T21:21:49.715845 - [SD Prompt Reader] 2024-11-21T21:21:49.715845 - Core version: 1.3.52024-11-21T21:21:49.715845 - 
2024-11-21T21:21:49.727412 - [ReActor]2024-11-21T21:21:49.728180 -  - 2024-11-21T21:21:49.728266 - STATUS2024-11-21T21:21:49.728266 -  - 2024-11-21T21:21:49.728266 - Running v0.5.2-a1 in ComfyUI2024-11-21T21:21:49.728266 - 
2024-11-21T21:21:49.914906 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2024-11-21T21:21:49.914906 - 
2024-11-21T21:21:49.918908 - Torch version: 2.4.1+cu1242024-11-21T21:21:49.921937 - 
2024-11-21T21:21:49.946937 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json2024-11-21T21:21:49.946937 - 
2024-11-21T21:21:49.955937 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json2024-11-21T21:21:49.956937 - 
2024-11-21T21:21:49.957898 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json2024-11-21T21:21:49.958905 - 
2024-11-21T21:21:49.974876 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json2024-11-21T21:21:49.974876 - 
2024-11-21T21:21:50.492214 - (pysssss:WD14Tagger) [DEBUG] Available ORT providers: TensorrtExecutionProvider, CUDAExecutionProvider, CPUExecutionProvider2024-11-21T21:21:50.492214 - 
2024-11-21T21:21:50.492214 - (pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider2024-11-21T21:21:50.492214 - 
2024-11-21T21:21:50.674814 - 
2024-11-21T21:21:50.674814 - From Bmad Custom Nodes2024-11-21T21:21:50.675779 - 
2024-11-21T21:21:50.675779 -  2024-11-21T21:21:50.675779 - Loaded 125 nodes:2024-11-21T21:21:50.675779 - 
2024-11-21T21:21:50.675779 -   + api nodes (14)2024-11-21T21:21:50.675779 - 
2024-11-21T21:21:50.675779 -   + simple utility nodes (58)2024-11-21T21:21:50.675779 - 
2024-11-21T21:21:50.676778 -   + CV nodes (50)2024-11-21T21:21:50.676778 - 
2024-11-21T21:21:50.676778 -   + color clip ade20k node (1)2024-11-21T21:21:50.676778 - 
2024-11-21T21:21:50.676778 -   + extension dependent nodes (2)2024-11-21T21:21:50.676778 - 
2024-11-21T21:21:50.676778 - 
2024-11-21T21:21:50.728231 - ------------------------------------------2024-11-21T21:21:50.729206 - 
2024-11-21T21:21:50.729206 - Comfyroll Studio v1.76 : 2024-11-21T21:21:50.729206 -  175 Nodes Loaded2024-11-21T21:21:50.729206 - 
2024-11-21T21:21:50.729206 - ------------------------------------------2024-11-21T21:21:50.729206 - 
2024-11-21T21:21:50.729206 - ** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md2024-11-21T21:21:50.729206 - 
2024-11-21T21:21:50.729206 - ** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki2024-11-21T21:21:50.730206 - 
2024-11-21T21:21:50.730206 - ------------------------------------------2024-11-21T21:21:50.730206 - 
2024-11-21T21:21:50.754206 - ### [START] ComfyUI AlekPet Nodes 2024-11-21T21:21:50.754206 - v1.0.332024-11-21T21:21:50.754206 -  ###2024-11-21T21:21:50.755205 - 
2024-11-21T21:21:52.055785 - Node -> ChatGLMNode: 2024-11-21T21:21:52.056786 - ChatGLM4TranslateCLIPTextEncodeNode, ChatGLM4TranslateTextNode2024-11-21T21:21:52.056786 -  2024-11-21T21:21:52.057786 - [Loading] 2024-11-21T21:21:52.057786 - 
2024-11-21T21:21:52.063316 - Node -> ArgosTranslateNode: 2024-11-21T21:21:52.063316 - ArgosTranslateCLIPTextEncodeNode, ArgosTranslateTextNode2024-11-21T21:21:52.063316 -  2024-11-21T21:21:52.064317 - [Loading] 2024-11-21T21:21:52.070314 - 
2024-11-21T21:21:52.072315 - Node -> DeepTranslatorNode: 2024-11-21T21:21:52.072315 - DeepTranslatorCLIPTextEncodeNode, DeepTranslatorTextNode2024-11-21T21:21:52.072315 -  2024-11-21T21:21:52.074342 - [Loading] 2024-11-21T21:21:52.075316 - 
2024-11-21T21:21:52.075774 - Node -> GoogleTranslateNode: 2024-11-21T21:21:52.075774 - GoogleTranslateCLIPTextEncodeNode, GoogleTranslateTextNode2024-11-21T21:21:52.075774 -  2024-11-21T21:21:52.075774 - [Loading] 2024-11-21T21:21:52.075774 - 
2024-11-21T21:21:52.082784 - Node -> PoseNode: 2024-11-21T21:21:52.082784 - PoseNode2024-11-21T21:21:52.082784 -  2024-11-21T21:21:52.082784 - [Loading] 2024-11-21T21:21:52.082784 - 
2024-11-21T21:21:52.086783 - Node -> ExtrasNode: 2024-11-21T21:21:52.086783 - PreviewTextNode, HexToHueNode, ColorsCorrectNode2024-11-21T21:21:52.086783 -  2024-11-21T21:21:52.087784 - [Loading] 2024-11-21T21:21:52.087784 - 
2024-11-21T21:21:52.165799 - Node -> IDENode: 2024-11-21T21:21:52.165799 - IDENode2024-11-21T21:21:52.165799 -  2024-11-21T21:21:52.165799 - [Loading] 2024-11-21T21:21:52.166785 - 
2024-11-21T21:21:52.450350 - Node -> PainterNode: 2024-11-21T21:21:52.450350 - PainterNode2024-11-21T21:21:52.450350 -  2024-11-21T21:21:52.450350 - [Loading] 2024-11-21T21:21:52.451350 - 
2024-11-21T21:21:52.451350 - ### [END] ComfyUI AlekPet Nodes ###2024-11-21T21:21:52.451350 - 
2024-11-21T21:21:53.295084 - FizzleDorf Custom Nodes: 2024-11-21T21:21:53.295084 - Loaded2024-11-21T21:21:53.295084 - 
2024-11-21T21:21:53.978989 - [tinyterraNodes] 2024-11-21T21:21:53.978989 - Loaded2024-11-21T21:21:53.978989 - 
2024-11-21T21:21:54.153520 - [comfy_mtb] | INFO -> loaded 2024-11-21T21:21:54.153520 - 882024-11-21T21:21:54.153520 -  nodes successfuly2024-11-21T21:21:54.154485 - 
2024-11-21T21:21:54.154485 - [comfy_mtb] | INFO -> Some nodes (2) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.2024-11-21T21:21:54.154485 - 
2024-11-21T21:21:54.173160 - Initializing ControlAltAI Nodes2024-11-21T21:21:54.173160 - 
2024-11-21T21:21:54.673906 - Eden_Comfy_Pipelines: WARNING: Could not find OPENAI_API_KEY in .env, disabling gpt prompt generation.2024-11-21T21:21:54.673906 - 
2024-11-21T21:21:54.777575 - Patching UNetModel.forward2024-11-21T21:21:54.777575 - 
2024-11-21T21:21:54.778576 - UNetModel.forward has been successfully patched.2024-11-21T21:21:54.778576 - 
2024-11-21T21:21:54.846045 - Nvidia APEX normalization not installed, using PyTorch LayerNorm2024-11-21T21:21:54.846045 - 
2024-11-21T21:21:54.969757 - 
2024-11-21T21:21:54.969757 - [rgthree-comfy] Loaded 42 fantastic nodes. 🎉2024-11-21T21:21:54.970759 - 
2024-11-21T21:21:54.970759 - 
2024-11-21T21:21:54.993757 - WAS Node Suite: 2024-11-21T21:21:54.993757 - BlenderNeko's Advanced CLIP Text Encode found, attempting to enable `CLIPTextEncode` support.2024-11-21T21:21:54.993757 - 
2024-11-21T21:21:54.993757 - WAS Node Suite: 2024-11-21T21:21:54.993757 - `CLIPTextEncode (BlenderNeko Advanced + NSP)` node enabled under `WAS Suite/Conditioning` menu.2024-11-21T21:21:54.993757 - 
2024-11-21T21:21:56.506917 - WAS Node Suite: 2024-11-21T21:21:56.507301 - OpenCV Python FFMPEG support is enabled2024-11-21T21:21:56.507301 - 
2024-11-21T21:21:56.507301 - WAS Node Suite 2024-11-21T21:21:56.507810 - Warning: 2024-11-21T21:21:56.507810 - `ffmpeg_bin_path` is not set in `F:\demo\backup\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.2024-11-21T21:21:56.507810 - 
2024-11-21T21:21:58.011701 - WAS Node Suite: 2024-11-21T21:21:58.011701 - Finished.2024-11-21T21:21:58.011701 -  2024-11-21T21:21:58.011701 - Loaded2024-11-21T21:21:58.011701 -  2024-11-21T21:21:58.012549 - 2192024-11-21T21:21:58.012693 -  2024-11-21T21:21:58.012693 - nodes successfully.2024-11-21T21:21:58.012693 - 
2024-11-21T21:21:58.012693 - 
	2024-11-21T21:21:58.012693 - "Every great dream begins with a dreamer."2024-11-21T21:21:58.012693 -  - Harriet Tubman2024-11-21T21:21:58.012693 - 
2024-11-21T21:21:58.013738 - 
2024-11-21T21:21:58.033743 - 
Import times for custom nodes:
2024-11-21T21:21:58.033743 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\websocket_image_save.py
2024-11-21T21:21:58.033743 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI_bitsandbytes_NF4
2024-11-21T21:21:58.033743 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\SD-Latent-Upscaler
2024-11-21T21:21:58.034744 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\sdxl_prompt_styler
2024-11-21T21:21:58.034867 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\comfyui-image-round
2024-11-21T21:21:58.034867 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\GenerateEncryptedKey
2024-11-21T21:21:58.034867 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-IC-Light-main
2024-11-21T21:21:58.034867 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-Logic
2024-11-21T21:21:58.034867 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\cg-use-everywhere
2024-11-21T21:21:58.035877 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI_Noise
2024-11-21T21:21:58.035877 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\Comfyui_TTP_Toolset
2024-11-21T21:21:58.035877 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUi_NNLatentUpscale
2024-11-21T21:21:58.035877 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI_FaceAnalysis
2024-11-21T21:21:58.036880 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\FreeU_Advanced
2024-11-21T21:21:58.036880 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-BRIA_AI-RMBG
2024-11-21T21:21:58.037265 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-11-21T21:21:58.037453 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
2024-11-21T21:21:58.037589 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\cg-image-picker
2024-11-21T21:21:58.037589 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI_TiledKSampler
2024-11-21T21:21:58.037589 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\stability-ComfyUI-nodes
2024-11-21T21:21:58.037589 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-YOLO
2024-11-21T21:21:58.037589 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\sd-perturbed-attention
2024-11-21T21:21:58.038600 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\efficiency-nodes-comfyui
2024-11-21T21:21:58.038600 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI_CryptoCat
2024-11-21T21:21:58.038600 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\masquerade-nodes-comfyui
2024-11-21T21:21:58.038600 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2024-11-21T21:21:58.038600 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
2024-11-21T21:21:58.038600 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI_InstantID
2024-11-21T21:21:58.039598 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyLiterals
2024-11-21T21:21:58.039598 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG
2024-11-21T21:21:58.039598 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\comfyUI_FrequencySeparation_RGB-HSV
2024-11-21T21:21:58.039598 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\wlsh_nodes
2024-11-21T21:21:58.039598 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\MistoControlNet-Flux-dev
2024-11-21T21:21:58.039598 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\comfyui-lama-remover
2024-11-21T21:21:58.039598 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-ELLA
2024-11-21T21:21:58.039598 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-11-21T21:21:58.039598 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-Image-Filters
2024-11-21T21:21:58.040598 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI_JPS-Nodes
2024-11-21T21:21:58.040598 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\comfyui-inpaint-nodes
2024-11-21T21:21:58.040598 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-Florence2
2024-11-21T21:21:58.040598 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ControlAltAI-Nodes
2024-11-21T21:21:58.040598 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-Kolors-MZ
2024-11-21T21:21:58.040598 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-Video-Matting
2024-11-21T21:21:58.040598 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-DDColor
2024-11-21T21:21:58.040598 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-Text_Image-Composite
2024-11-21T21:21:58.040598 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\Comfyui_CXH_joy_caption
2024-11-21T21:21:58.040598 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-TiledDiffusion
2024-11-21T21:21:58.040598 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-Flowty-LDSR
2024-11-21T21:21:58.041599 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\comfyui-animatediff
2024-11-21T21:21:58.041599 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\comfyui-various
2024-11-21T21:21:58.041599 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-PixelOE
2024-11-21T21:21:58.041599 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-11-21T21:21:58.041599 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\comfy-image-saver
2024-11-21T21:21:58.041599 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-11-21T21:21:58.041599 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI_essentials
2024-11-21T21:21:58.041599 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyMath
2024-11-21T21:21:58.041599 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-KwaiKolorsWrapper
2024-11-21T21:21:58.041599 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\mikey_nodes
2024-11-21T21:21:58.042598 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-11-21T21:21:58.042598 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
2024-11-21T21:21:58.042598 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-GGUF
2024-11-21T21:21:58.042598 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
2024-11-21T21:21:58.042598 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-11-21T21:21:58.042598 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
2024-11-21T21:21:58.042598 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-IC-Light
2024-11-21T21:21:58.042598 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\comfyui-prompt-reader-node
2024-11-21T21:21:58.043600 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-Whisper
2024-11-21T21:21:58.043600 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-LivePortraitKJ
2024-11-21T21:21:58.043600 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\rgthree-comfy
2024-11-21T21:21:58.043600 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI_inpaintpreprocessor
2024-11-21T21:21:58.043600 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\comfyui_bmad_nodes
2024-11-21T21:21:58.043600 -    0.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI_smZNodes
2024-11-21T21:21:58.043600 -    0.1 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-11-21T21:21:58.043600 -    0.1 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-11-21T21:21:58.043600 -    0.1 seconds: F:\demo\backup\ComfyUI\custom_nodes\comfyui-dream-project
2024-11-21T21:21:58.044601 -    0.1 seconds: F:\demo\backup\ComfyUI\custom_nodes\facerestore_cf
2024-11-21T21:21:58.044601 -    0.1 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
2024-11-21T21:21:58.044601 -    0.1 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
2024-11-21T21:21:58.044601 -    0.1 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-InstantID
2024-11-21T21:21:58.044601 -    0.1 seconds: F:\demo\backup\ComfyUI\custom_nodes\comfy_mtb
2024-11-21T21:21:58.044601 -    0.1 seconds: F:\demo\backup\ComfyUI\custom_nodes\Comfyui-ergouzi-Nodes
2024-11-21T21:21:58.044601 -    0.1 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-segment-anything-2
2024-11-21T21:21:58.045599 -    0.1 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI_BiRefNet_ll
2024-11-21T21:21:58.045599 -    0.1 seconds: F:\demo\backup\ComfyUI\custom_nodes\PuLID_ComfyUI
2024-11-21T21:21:58.045599 -    0.2 seconds: F:\demo\backup\ComfyUI\custom_nodes\comfyui_segment_anything
2024-11-21T21:21:58.045599 -    0.2 seconds: F:\demo\backup\ComfyUI\custom_nodes\comfyui-tensorops
2024-11-21T21:21:58.045599 -    0.2 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-SUPIR
2024-11-21T21:21:58.045599 -    0.2 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-BiRefNet-ZHO
2024-11-21T21:21:58.045599 -    0.2 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-Crystools
2024-11-21T21:21:58.046598 -    0.3 seconds: F:\demo\backup\ComfyUI\custom_nodes\comfyui-reactor-node
2024-11-21T21:21:58.046598 -    0.3 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper
2024-11-21T21:21:58.046598 -    0.4 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-Bringing-Old-Photos-Back-to-Life
2024-11-21T21:21:58.046598 -    0.4 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI_LayerStyle
2024-11-21T21:21:58.046598 -    0.4 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI_FizzNodes
2024-11-21T21:21:58.046598 -    0.5 seconds: F:\demo\backup\ComfyUI\custom_nodes\eden_comfy_pipelines
2024-11-21T21:21:58.047597 -    0.5 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-Manager
2024-11-21T21:21:58.047597 -    0.5 seconds: F:\demo\backup\ComfyUI\custom_nodes\clipseg.py
2024-11-21T21:21:58.047597 -    0.5 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-Easy-Use
2024-11-21T21:21:58.047597 -    0.8 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-BrushNet
2024-11-21T21:21:58.047597 -    0.9 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait
2024-11-21T21:21:58.047597 -    1.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-Allor
2024-11-21T21:21:58.047597 -    1.1 seconds: F:\demo\backup\ComfyUI\custom_nodes\comfyui-art-venture
2024-11-21T21:21:58.047597 -    1.2 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-Inspyrenet-Rembg
2024-11-21T21:21:58.047597 -    1.6 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-DynamiCrafter
2024-11-21T21:21:58.047597 -    2.1 seconds: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
2024-11-21T21:21:58.048597 -    3.0 seconds: F:\demo\backup\ComfyUI\custom_nodes\was-node-suite-comfyui
2024-11-21T21:21:58.048597 - 
2024-11-21T21:21:58.071631 - Starting server

2024-11-21T21:21:58.072599 - To see the GUI go to: http://127.0.0.1:8188
2024-11-21T21:22:00.546489 - FETCH DATA from: F:\demo\backup\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json2024-11-21T21:22:00.553490 -  [DONE]2024-11-21T21:22:00.553490 - 
2024-11-21T21:22:54.010706 - got prompt
2024-11-21T21:22:54.295982 - !!! Exception during processing !!! name 'apply_gaussian_blur' is not defined
2024-11-21T21:22:54.309563 - Traceback (most recent call last):
  File "F:\demo\backup\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\demo\backup\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\demo\backup\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\demo\backup\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\demo\backup\ComfyUI\custom_nodes\Comfyui_TTP_Toolset\TTP_toolsets.py", line 52, in process_image
    img_np = apply_gaussian_blur(resized_img, ksize=int(blur_strength), sigmaX=blur_strength / 2)
             ^^^^^^^^^^^^^^^^^^^
NameError: name 'apply_gaussian_blur' is not defined

2024-11-21T21:22:54.309563 - Prompt executed in 0.22 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by Daggle24** [comment]
same issue here

**Comment by EasyComfyui** [comment]
> Vấn đề tương tự ở đây
> 
> Đã sửa bằng cách thêm
> 
> ```
> def apply_gaussian_blur(image_np, ksize=5, sigmaX=1.0):
>     if ksize % 2 == 0:
>         ksize += 1  # ksize must be odd
>     blurred_image = cv2.GaussianBlur(image_np, (ksize, ksize), sigmaX=sigmaX)
>     return blurred_image
> ```
> 
> trong tệp TTP_ toolsets.py

thanks, it work!!

**Comment by tenikis** [comment]
> TTP_ toolsets.py

Where in TTP_ toolsets.py do you put this please?


def apply_gaussian_blur(image_np, ksize=5, sigmaX=1.0):
    if ksize % 2 == 0:
        ksize += 1  # ksize must be odd
    blurred_image = cv2.GaussianBlur(image_np, (ksize, ksize), sigmaX=sigmaX)
    return blurred_image


thanks
